# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZmRhYmI0Y2I1M2FiY2VhYTQ0NzVlMGQzZTJjZGJkZjU3YzVjOWJiYjEyM2RjMTQ2MWQ4MzQzZTcxZTRjZTUxN2E5ZTVhN2IwNzU0OTljZmVkNDdmOGM3NWFkYzMwNjQyZjcyZTQ5MmYwMTM0MjA1NGVhMjgyYzA5NTc1NDNhOWM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
